<?php

function sum_numbers_menu(){
  $items = array();

  $items['sum_numbers'] = array(
    'title' => 'Sum Spectacular!',
    'description' => 'A form that will add two integers',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sum_numbers_form'),
    'access callback' => TRUE
  );
  return

$items;
}

function sum_numbers_form($form, &$form_state) {

  $form['first'] = array(
    '#type' => 'textfield',
    '#title' => 'First number:',
    '#required' => TRUE,
    '#element_validate' => array('element_validate_number'),
  );

  $form['second'] = array(
    '#type' => 'textfield',
    '#title' => 'Second number:',
    '#required' => TRUE,
    '#element_validate' => array('element_validate_number'),
  );

  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Add numbers!'),
    '#required' => TRUE,
  );
  return $form;
}

function sum_numbers_form_submit($form, &$form_state) {
  $first_number = $form_state['values']['first'];
  $second_number = $form_state['values']['second'];
  drupal_set_message(t("The sum of your numbers is: " . ($first_number + $second_number)));
}