<?php

function sum_numbers_menu(){
  $items = array();

  $items['sum_numbers'] = array(
    'title' => 'Sum Spectacular!',
    'description' => 'A form that will add two integers',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sum_numbers_form'),
    'access callback' => TRUE
  );
  return

$items;
}

function sum_numbers_form($form, &$form_state) {

  $form['first'] = array(
    '#type' => 'textfield',
    '#title' => 'First number:',
    '#required' => TRUE,
  );

  $form['second'] = array(
    '#type' => 'textfield',
    '#title' => 'Second number:',
    '#required' => TRUE,
  );

  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Add numbers!'),
    '#required' => TRUE,
  );
  return $form;
}